// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAvwZpTAUe1mb6Kgn_TOovHEJ_QpGPtpc',
    appId: '1:670900854214:web:9a915f00a37022430226c7',
    messagingSenderId: '670900854214',
    projectId: 'baddie-app-version',
    authDomain: 'baddie-app-version.firebaseapp.com',
    storageBucket: 'baddie-app-version.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIdyzmPbuA-kO81nYGZCQ3BdJ0IPon2c',
    appId: '1:670900854214:android:ab3d2711046ffffe0226c7',
    messagingSenderId: '670900854214',
    projectId: 'baddie-app-version',
    storageBucket: 'baddie-app-version.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJnEJuphJAdN7Jr82pX0gCssYUhXHzwo',
    appId: '1:670900854214:ios:b216bd89592bef640226c7',
    messagingSenderId: '670900854214',
    projectId: 'baddie-app-version',
    storageBucket: 'baddie-app-version.firebasestorage.app',
    iosBundleId: 'com.example.baddieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdJnEJuphJAdN7Jr82pX0gCssYUhXHzwo',
    appId: '1:670900854214:ios:b216bd89592bef640226c7',
    messagingSenderId: '670900854214',
    projectId: 'baddie-app-version',
    storageBucket: 'baddie-app-version.firebasestorage.app',
    iosBundleId: 'com.example.baddieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAvwZpTAUe1mb6Kgn_TOovHEJ_QpGPtpc',
    appId: '1:670900854214:web:35b28d1985344d090226c7',
    messagingSenderId: '670900854214',
    projectId: 'baddie-app-version',
    authDomain: 'baddie-app-version.firebaseapp.com',
    storageBucket: 'baddie-app-version.firebasestorage.app',
  );
}
